-- Creation script for RujelSync model --

CREATE DATABASE `RujelSync` DEFAULT CHARACTER SET utf8;
USE `RujelSync`;

CREATE TABLE IF NOT EXISTS SYNC_EXT_SYSTEM (
  S_ID smallint NOT NULL,
  PRODUCT_NAME varchar(255),
  BASE_IDENTIFIER varchar(255) NOT NULL,
  PRIMARY KEY (S_ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS SYNC_EXT_DATA (
  D_ID integer NOT NULL,
  SYSTEM_ID smallint NOT NULL,
  DATA_KEY varchar(28) NOT NULL,
  DATA_VALUE text,
  PRIMARY KEY (D_ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS SYNC_MATCH (
  M_ID integer NOT NULL,
  SYSTEM_ID smallint NOT NULL,
  ENTITY_ID smallint NOT NULL,
  OBJECT_ID integer NOT NULL,
  EXTERNAL_ID varchar(255),
  EDU_YEAR smallint,
  PRIMARY KEY (M_ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS SYNC_INDEX (
  I_ID integer NOT NULL,
  SYSTEM_ID smallint NOT NULL,
  INDEX_NAME varchar(28) NOT NULL,
  EDU_YEAR smallint,
  PRIMARY KEY (I_ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS SYNC_IDX_MATCH (
  M_ID integer NOT NULL,
  INDEX_ID integer NOT NULL,
  LOCAL_VALUE varchar(255),
  EXT_VALUE varchar(255),
  PRIMARY KEY (M_ID)
) ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS EO_PK_TABLE (
  NAME char(40),
  PK int
);

CREATE TABLE IF NOT EXISTS SCHEMA_VERSION (
  MODEL_NAME varchar(255),
  VERSION_NUMBER smallint unsigned NOT NULL,
  VERSION_TITLE varchar(255),
  INSTALL_DATE timestamp
);

INSERT INTO SCHEMA_VERSION (MODEL_NAME,VERSION_NUMBER,VERSION_TITLE)
  VALUES ('RujelSync',1,'0.9.4');
