package net.rujel.diary;

import java.text.ParsePosition;

import net.rujel.base.MyUtility;

import com.webobjects.appserver.*;
import com.webobjects.foundation.NSTimestamp;

// Generated by the WOLips Templateengine Plug-in at Jan 21, 2009 11:38:15 AM
public class DateField extends com.webobjects.appserver.WOComponent {
 	public DateField(WOContext context) {
        super(context);
    }

 	public String fieldName;
    public String value;
    public String className;
    public String onEnter;
    public String onBlur;

	public void appendToResponse(WOResponse aResponse, WOContext aContext) {
		WORequest req = aContext.request();
		fieldName = (String)valueForBinding("name");
		value = req.stringFormValueForKey(fieldName);
		NSTimestamp date = (NSTimestamp)valueForBinding("date");
		if(date != null) {
			value = MyUtility.dateFormat().format(date);
		} else {
			try {
				date = (NSTimestamp)MyUtility.dateFormat().parseObject(value);
			} catch (Exception e) {
				className = "default";
				onEnter = "this.className='';";
				onBlur = "if(value==defaultValue)className='default';";
				String base = (String)valueForBinding("baseName");
				base = req.stringFormValueForKey(base);
				date = (NSTimestamp)MyUtility.dateFormat().parseObject(base, new ParsePosition(0));
				if(date == null)
					date = new NSTimestamp();
				Integer shift = (Integer)valueForBinding("shift");
				if(shift != null)
					date = date.timestampByAddingGregorianUnits(0, 0, shift.intValue(), 0, 0, 0);
				value = MyUtility.dateFormat().format(date);
			}
			if(hasBinding("date"))
				setValueForBinding(date, "date");
		}
		super.appendToResponse(aResponse, aContext);
	}
 
    public boolean synchronizesVariablesWithBindings() {
        return false;
	}
	
    public boolean isStateless() {
		return true;
	}
	
	public void reset() {
		value = null;
		className = null;
		onEnter = null;
		onBlur = null;
		super.reset();
	}
}