package net.rujel.diary;

import com.webobjects.appserver.*;

// Generated by the WOLips Templateengine Plug-in at Jan 21, 2009 1:49:16 PM
public class ErrorPage extends com.webobjects.appserver.WOComponent {
    public Throwable throwable;

	public ErrorPage(WOContext context) {
        super(context);
    }
}