// ByCoursePresenter.java: Class file for WO Component 'ByCoursePresenter'

/*
 * Copyright (c) 2008, Gennady & Michael Kushnir
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without modification, are
 * permitted provided that the following conditions are met:
 * 
 * 	•	Redistributions of source code must retain the above copyright notice, this
 * 		list of conditions and the following disclaimer.
 * 	•	Redistributions in binary form must reproduce the above copyright notice,
 * 		this list of conditions and the following disclaimer in the documentation
 * 		and/or other materials provided with the distribution.
 * 	•	Neither the name of the RUJEL nor the names of its contributors may be used
 * 		to endorse or promote products derived from this software without specific 
 * 		prior written permission.
 * 		
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
 * SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 * TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY
 * WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package net.rujel.ui;

import net.rujel.base.SettingsBase;
import net.rujel.reusables.NamedFlags;
import net.rujel.reusables.Various;
import net.rujel.reusables.WOLogLevel;

import com.webobjects.appserver.*;
import com.webobjects.eocontrol.EOEditingContext;
import com.webobjects.eocontrol.EOEnterpriseObject;
import com.webobjects.foundation.NSKeyValueCoding;
import com.webobjects.foundation.NSMutableArray;

// Generated by the WOLips Templateengine Plug-in at Jul 17, 2009 3:54:08 PM
public class ByCoursePresenter extends com.webobjects.appserver.WOComponent {
	
	protected NSKeyValueCoding _bc;
	
    public ByCoursePresenter(WOContext context) {
        super(context);
    }
    
    public NSKeyValueCoding bc() {
    	if(_bc == null)
    		_bc = (NSKeyValueCoding)valueForBinding("value");
    	return _bc;
    }
    
    protected NamedFlags _access;
    public NamedFlags access() {
    	if(_access != null)
    		return _access;
    	_access = (NamedFlags)valueForBinding("access");
    	if(_access != null)
    		return _access;
    	_access = (NamedFlags)session().valueForKeyPath("readAccess.FLAGS.SettingByCourse");
    	return _access;
    }
    
	public String editorHead() {
    	if(Various.boolForObject(valueForBinding("readOnly")))
    		return null;
    	NamedFlags access = (NamedFlags)valueForBinding("access");
    	if(access == null)
    		access = (NamedFlags)session().valueForKeyPath("readAccess.FLAGS.SettingByCourse");
    	if(access.flagForKey("edit") || access.flagForKey("delete")) {
    		if(access.flagForKey("edit") && access.flagForKey("delete"))
    			return "<td colspan = \"2\"/>";
    		else
    			return "<td/>";
    	}
    	return null;
	}
	
    public boolean isBase() {
    	return (bc() instanceof SettingsBase);
    }
    
    public String groupStyle() {
    	if(bc().valueForKey("course") != null)
    		return null;
    	if(bc().valueForKey("eduGroup") != null)
    		return "gerade";
    	if(bc().valueForKey("grade") != null)
    		return "highlight";
    	return null;
    }

    public String subjectStyle() {
    	if(bc().valueForKey("course") != null)
    		return null;
    	if(bc().valueForKey("cycle") != null)
    		return "ungerade";
    	return null;
    }

    public String teacherStyle() {
    	if(bc().valueForKey("course") != null)
    		return null;
    	if(bc().valueForKey("teacher") != null)
    		return "green";
    	return null;
    }

    public boolean isStateless() {
		return true;
	}
	public boolean synchronizesVariablesWithBindings() {
        return false;
	}
	
	public void reset() {
		_bc = null;
		super.reset();
	}

	public WOActionResults edit() {
		WOComponent editor = pageWithName("ByCourseEditor");
		editor.takeValueForKey(context().page(), "returnPage");
		editor.takeValueForKey(bc(), "byCourse");
		editor.takeValueForKey(valueForBinding("editList"), "editList");
    	if(hasBinding("pushByCourse")) {
    		editor.takeValueForKey(this, "resultGetter");
    		editor.takeValueForKey("^pushByCourse", "pushToKeyPath");
    	}
		return editor;
	}
	
	public void delete() {
		if(!(bc() instanceof EOEnterpriseObject))
			return;
		EOEnterpriseObject bc = (EOEnterpriseObject)bc();
		EOEditingContext ec = bc.editingContext();
		ec.lock();
		SettingsBase base = null;
		if(bc instanceof SettingsBase)
			base = (SettingsBase)bc;
		else
			base = (SettingsBase)bc.valueForKey("settingsBase");
		try {
			ec.deleteObject(bc);
			ByCourseEditor.logger.log(WOLogLevel.COREDATA_EDITING,"Deleting SettingByCourse: "
					+ base.key(), new Object[] {session(),bc.valueForKey("settingsBase")});
			String path = (String)valueForBinding("pushByCourse");
			if(path != null) {
				WOComponent getter = parent();
	    		while (path.charAt(0) == '^') {
	    			path = path.substring(1);
					path = (String)getter.valueForBinding(path);
					getter = getter.parent();
				}
	    		getter.takeValueForKeyPath(bc, path);
			}
			ec.saveChanges();
			NSMutableArray list = (NSMutableArray)valueForBinding("editList");
			if(list != null)
				list.removeObject(bc);
		} catch (Exception e) {
			ByCourseEditor.logger.log(WOLogLevel.INFO,"Could not delete SettingByCourse: "
					+ base.key(), new Object[] {session(),bc,e});
			session().takeValueForKey(e.getMessage(), "message");
		} finally {
			ec.unlock();
		}
	}
}