package net.rujel.autoitog;

import java.text.SimpleDateFormat;

import net.rujel.criterial.BorderSet;
import net.rujel.eduresults.ItogContainer;
import net.rujel.reusables.NamedFlags;
import net.rujel.reusables.SettingsReader;

import com.webobjects.appserver.*;
import com.webobjects.eoaccess.EOUtilities;
import com.webobjects.foundation.NSArray;
import com.webobjects.foundation.NSDictionary;

// Generated by the WOLips Templateengine Plug-in at Sep 11, 2009 11:25:34 AM
public class AutoItogEditor extends com.webobjects.appserver.WOComponent {
	
	public WOComponent returnPage;
	public ItogContainer itog;
	public AutoItog autoItog;
	public String listName;
	
	public NSArray bsets;
	public NSArray calculators;
	public Object item;
	public NSDictionary calc;
	public String fireDate;
	public String fireTime;
	public BorderSet borderSet;
	public NamedFlags namedFlags;
	
    public AutoItogEditor(WOContext context) {
        super(context);
        calculators = (NSArray)context.session().valueForKeyPath(
						"strings.RujelAutoItog_AutoItog.calculators");
    }
    
    public void setItog(ItogContainer itogContainer) {
    	itog = itogContainer;
    	bsets = EOUtilities.objectsForEntityNamed(
    			itog.editingContext(), BorderSet.ENTITY_NAME);
    }
    
    public void setAutoItog(AutoItog ai) {
    	autoItog = ai;
    	if(ai == null)
    		return;
    	listName = ai.listName();
		String pattern = autoItog.calculatorName();
		if(pattern != null) { // resolve className to readable title
			for (int i = 0; i < calculators.count(); i++) {
				calc = (NSDictionary)calculators.objectAtIndex(i);
				if(pattern.equals(calc.valueForKey("className"))) {
					break;
				}
				calc = null;
			}
		}
		pattern = SettingsReader.stringForKeyPath("ui.shortDateFormat","MM-dd");
		SimpleDateFormat format = new SimpleDateFormat(pattern);
		fireDate = format.format(ai.fireDate());
		format = new SimpleDateFormat("HH:mm");
		fireTime = format.format(ai.fireTime());
		borderSet = ai.borderSet();
		namedFlags = ai.namedFlags();
    }
}