package net.rujel.vselists;

import net.rujel.interfaces.Person;
import net.rujel.interfaces.Student;

import com.webobjects.appserver.*;
import com.webobjects.eoaccess.EOUtilities;
import com.webobjects.foundation.NSArray;

// Generated by the WOLips Templateengine Plug-in at Aug 28, 2009 8:23:02 PM
public class StudentEditor extends com.webobjects.appserver.WOComponent {
	public VseStudent student;
	
    public StudentEditor(WOContext context) {
        super(context);
    }
    
    public NSArray students() {
    	Person person = (Person)valueForBinding("person");
    	return students(person);
    }
    
    public static NSArray students(Person person) {
    	return EOUtilities.objectsMatchingKeyAndValue(person.editingContext(),
    			Student.entityName, "person", person);
    }
    
	public boolean isStateless() {
		return true;
	}
	
	public boolean synchronizesVariablesWithBindings() {
        return false;
	}
}