package net.rujel.vselists;

import net.rujel.interfaces.Person;

import com.webobjects.appserver.*;
import com.webobjects.eoaccess.EOUtilities;
import com.webobjects.foundation.NSArray;

// Generated by the WOLips Templateengine Plug-in at Aug 31, 2009 3:02:08 PM
public class TeacherEditor extends com.webobjects.appserver.WOComponent {
	public VseTeacher teacher;
	
    public TeacherEditor(WOContext context) {
        super(context);
    }
    
    public NSArray teachers() {
    	Person person = (Person)valueForBinding("person");
    	return teachers(person);
    }
    
    public static NSArray teachers(Person person) {
    	return EOUtilities.objectsMatchingKeyAndValue(person.editingContext(),
    			VseTeacher.ENTITY_NAME, "person", person);
    }
    
	public boolean isStateless() {
		return true;
	}
	
	public boolean synchronizesVariablesWithBindings() {
        return false;
	}
}