// Main.java : Class file for WO Component 'Main'

/*
 * Copyright (c) 2008, Gennady & Michael Kushnir
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without modification, are
 * permitted provided that the following conditions are met:
 * 
 * 	•	Redistributions of source code must retain the above copyright notice, this
 * 		list of conditions and the following disclaimer.
 * 	•	Redistributions in binary form must reproduce the above copyright notice,
 * 		this list of conditions and the following disclaimer in the documentation
 * 		and/or other materials provided with the distribution.
 * 	•	Neither the name of the RUJEL nor the names of its contributors may be used
 * 		to endorse or promote products derived from this software without specific 
 * 		prior written permission.
 * 		
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
 * SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 * TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY
 * WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package net.rujel.ui;

import net.rujel.reusables.SettingsReader;

import com.webobjects.appserver.*;

// Generated by the WOLips Templateengine Plug-in at Oct 24, 2008 2:36:25 PM
public class Main extends com.webobjects.appserver.WOComponent {	
    public String message;
    public int timeout = 0;

    public Main(WOContext context) {
        super(context);
    }
    
    public String login(){
        return context().request().stringFormValueForKey("username");
    }
    
    public boolean noGuest() {
    	return SettingsReader.boolForKeyPath("auth.noGuest", false);
    }

    public String guestUser() {
    	return SettingsReader.stringForKeyPath("auth.guestUser", null);
    }
    
    public String guestPassword() {
    	return SettingsReader.stringForKeyPath("auth.guestPassword", null);
    }
    
    public String guestOnClick() {
    	if(guestUser() != null)
    		return "guest(form);";
    	StringBuilder buf = new StringBuilder("window.location = '");
    	buf.append(context().directActionURLForActionNamed("guest", null));
    	buf.append("';");
    	return buf.toString();
    }
    
    public String version() {
    	return System.getProperty("RujelVersion");
    }
}