// Curriculum.java: Class file for WO Component 'Curriculum'

/*
 * Copyright (c) 2008, Gennady & Michael Kushnir
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without modification, are
 * permitted provided that the following conditions are met:
 * 
 * 	•	Redistributions of source code must retain the above copyright notice, this
 * 		list of conditions and the following disclaimer.
 * 	•	Redistributions in binary form must reproduce the above copyright notice,
 * 		this list of conditions and the following disclaimer in the documentation
 * 		and/or other materials provided with the distribution.
 * 	•	Neither the name of the RUJEL nor the names of its contributors may be used
 * 		to endorse or promote products derived from this software without specific 
 * 		prior written permission.
 * 		
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
 * SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 * TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY
 * WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package net.rujel.curriculum;

import java.io.InputStream;
import java.util.logging.Logger;

import net.rujel.reusables.WOLogLevel;

import com.webobjects.appserver.*;
import com.webobjects.foundation.*;
import com.webobjects.foundation.NSKeyValueCoding;

// Generated by the WOLips Templateengine Plug-in at Jan 29, 2009 1:57:26 PM
public class Curriculum extends com.webobjects.appserver.WOComponent {
	
	
	public NSArray availableRegimes;
	public NSKeyValueCoding currTab;
	public NSDictionary plist;
	public NSKeyValueCoding itemDict;
	public NSMutableDictionary params = new NSMutableDictionary();
	
    public Curriculum(WOContext context) {
        super(context);
        try {
			InputStream pstream = application().resourceManager()
					.inputStreamForResourceNamed("Overview.plist",
							"RujelCurriculum", null);
			NSData pdata = new NSData(pstream, pstream.available());
			plist = (NSDictionary)NSPropertyListSerialization.propertyListFromData(
								pdata, "utf8");
			//availableRegimes = (NSArray)session().valueForKeyPath("modules.curriculumRegime");
		} catch (Exception e) {
			Object[] args = new Object[] {session(),e};
			Logger.getLogger("rujel.curriculum").log(WOLogLevel.WARNING,
					"Error reading Overview.pist",args);
		}
    }
    
}