package net.rujel.curriculum;

import com.webobjects.appserver.*;

// Generated by the WOLips Templateengine Plug-in at Mar 21, 2009 10:54:12 PM
public class ReasonPresenter extends com.webobjects.appserver.WOComponent {
    public ReasonPresenter(WOContext context) {
        super(context);
    }
    
	public boolean isStateless() {
		return true;
	}
	
	public boolean synchronizesVariablesWithBindings() {
        return false;
	}

	public void reset() {
		super.reset();
	}
}