// SubsReport.java

/*
 * Copyright (c) 2008, Gennady & Michael Kushnir
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without modification, are
 * permitted provided that the following conditions are met:
 * 
 * 	•	Redistributions of source code must retain the above copyright notice, this
 * 		list of conditions and the following disclaimer.
 * 	•	Redistributions in binary form must reproduce the above copyright notice,
 * 		this list of conditions and the following disclaimer in the documentation
 * 		and/or other materials provided with the distribution.
 * 	•	Neither the name of the RUJEL nor the names of its contributors may be used
 * 		to endorse or promote products derived from this software without specific 
 * 		prior written permission.
 * 		
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
 * SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 * TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY
 * WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package net.rujel.curriculum;

import java.text.FieldPosition;
import java.text.SimpleDateFormat;
import java.util.Date;

import net.rujel.interfaces.*;
import net.rujel.reusables.SessionedEditingContext;

import com.webobjects.appserver.*;
import com.webobjects.foundation.*;

// Generated by the WOLips Templateengine Plug-in at Oct 10, 2008 12:25:34 PM
public class SubsReport extends com.webobjects.appserver.WOComponent {
    public SubsReport(WOContext context) {
        super(context);
    }
    
    public NSTimestamp begin;
    public NSTimestamp end;
    public SessionedEditingContext ec = new SessionedEditingContext(session());
    
    //public NSArray substitutes;
    public Substitute subsItem;    

    public void appendToResponse(WOResponse aResponse, WOContext aContext) {
    	Substitute.checkSubstitutes(substitutes());
     	super.appendToResponse(aResponse, aContext);
    	aResponse.setHeader("application/octet-stream","Content-Type");
    	//aResponse.setHeader("text/plain","Content-Type");
		SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd");
		StringBuffer buf = new StringBuffer("attachment; filename=\"");
		sdf.format(new Date(), buf,new FieldPosition(SimpleDateFormat.YEAR_FIELD));
		buf.append(".tab\"");
		aResponse.setHeader(buf.toString(),"Content-Disposition");
    }

    public NSArray substitutes() {
    	Integer school = (Integer)session().valueForKey("school");
    	return Substitute.substitutesForPeriod(ec, begin, end, school);
    	//return substitutes;
    }

    public String substitutor() {
    	Teacher teacher = subsItem.teacher();
		if(teacher == null)
			return null;
		return Person.Utility.fullName(teacher, true, 2, 1, 1);
	}

	public String teacherOrig() {
		Teacher teacher = (Teacher)subsItem.valueForKeyPath("lesson.course.teacher");
		if(teacher == null)
			return null;
		return Person.Utility.fullName(teacher, true, 2, 1, 1);
	}
}