// SubsTypeSelector.java: Class file for WO Component 'SubsTypeSelector'

/*
 * Copyright (c) 2008, Gennady & Michael Kushnir
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without modification, are
 * permitted provided that the following conditions are met:
 * 
 * 	•	Redistributions of source code must retain the above copyright notice, this
 * 		list of conditions and the following disclaimer.
 * 	•	Redistributions in binary form must reproduce the above copyright notice,
 * 		this list of conditions and the following disclaimer in the documentation
 * 		and/or other materials provided with the distribution.
 * 	•	Neither the name of the RUJEL nor the names of its contributors may be used
 * 		to endorse or promote products derived from this software without specific 
 * 		prior written permission.
 * 		
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
 * SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 * TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY
 * WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package net.rujel.curriculum;

import net.rujel.interfaces.EduLesson;

import com.webobjects.appserver.*;
import com.webobjects.appserver.WOActionResults;

// Generated by the WOLips Templateengine Plug-in at Oct 2, 2009 2:04:12 PM
public class SubsTypeSelector extends com.webobjects.appserver.WOComponent {

	public WOComponent returnPage;
    public EduLesson lesson;
    
    public SubsTypeSelector(WOContext context) {
        super(context);
    }
    
    public void setSubstitute(Object sub) {
    	;
    }
    
    public WOActionResults addSubstitute() {
		WOComponent editor = pageWithName("EditSubstitute");
		editor.takeValueForKey(returnPage, "returnPage");
		editor.takeValueForKey(lesson, "lesson");	    	
		editor.takeValueForKey(null, "substitute");
		return (WOActionResults)editor.valueForKey("initial");
    }
    
    public WOActionResults addJoinSub() {
		WOComponent editor = pageWithName("EditSubstitute");
		editor.takeValueForKey(returnPage, "returnPage");
		editor.takeValueForKey(lesson, "lesson");	    	
		editor.takeValueForKey(null, "substitute");
		editor.takeValueForKey(new Integer(1), "idx");
		return editor;
    }
    
    public WOActionResults addJoin() {
		WOComponent editor = pageWithName("EditJoin");
		editor.takeValueForKey(returnPage, "returnPage");
		editor.takeValueForKey(lesson, "lesson");	    	
		return editor;
    }

	public WOActionResults addVariarion() {
		WOComponent editor = pageWithName("EditVarSub");
		editor.takeValueForKey(returnPage, "returnPage");
		editor.takeValueForKey(lesson, "lesson");
		if(editor.valueForKey("fromCourse") == null)
			editor.valueForKey("prepareCourses");
		return editor;
	}
}