package net.rujel.complete;

import java.util.Enumeration;

import net.rujel.base.SettingsBase;
import net.rujel.eduplan.EduPeriod;
import net.rujel.interfaces.EduCourse;
import net.rujel.interfaces.EduCycle;
import net.rujel.interfaces.Person;
import net.rujel.reusables.SessionedEditingContext;
import net.rujel.reusables.Various;
import net.rujel.reusables.FileWriterUtil;

import com.webobjects.appserver.*;
import com.webobjects.eoaccess.EOUtilities;
import com.webobjects.eocontrol.EOAndQualifier;
import com.webobjects.eocontrol.EOEditingContext;
import com.webobjects.eocontrol.EOFetchSpecification;
import com.webobjects.eocontrol.EOKeyGlobalID;
import com.webobjects.eocontrol.EOKeyValueQualifier;
import com.webobjects.eocontrol.EOQualifier;
import com.webobjects.eocontrol.EOSortOrdering;
import com.webobjects.foundation.NSArray;
import com.webobjects.foundation.NSDictionary;
import com.webobjects.foundation.NSKeyValueCoding;
import com.webobjects.foundation.NSMutableDictionary;
import com.webobjects.foundation.NSTimestamp;

// Generated by the WOLips Templateengine Plug-in at Jun 22, 2009 1:21:03 PM
public class CoursesCatalog extends com.webobjects.appserver.WOComponent {
	protected static final EOSortOrdering[] orders = new EOSortOrdering[] {
		new EOSortOrdering("eduGroup",EOSortOrdering.CompareAscending),
		new EOSortOrdering("cycle",EOSortOrdering.CompareAscending),
		new EOSortOrdering("teacher",EOSortOrdering.CompareAscending)
	};
	public static final NSArray byClass = new NSArray(orders);
	public static final NSArray bySubject = new NSArray(
			new EOSortOrdering[] {orders[1],orders[0],orders[2]});
	public static final NSArray byTeacher = new NSArray(
			new EOSortOrdering[] {orders[2],orders[0],orders[1]});
	
	
	public EOEditingContext ec;
	public NSArray allCourses;
	public String grouping;
	public EduCourse item;
	public Object courseID;
	public String grHead;
	public NSKeyValueCoding catalog;
	public boolean sections;
	
    public CoursesCatalog(WOContext context) {
        super(context);
    	sections = Various.boolForObject(WOApplication.application().valueForKeyPath(
			"strings.sections.hasSections")) && EduCycle.entityName.equals("PlanCycle");
    }
    
    public NSArray types() { 
    	return new NSArray(new String[] {"eduGroup","cycle","teacher"});
    }
    
    public NSArray allCourses() {
    	EOQualifier qual = null;
    	if(sections && !grouping.equals("teacher")) {
    		qual = new EOKeyValueQualifier("cycle.section", EOQualifier.QualifierOperatorEqual, 
    					 session().valueForKeyPath("state.section.idx"));
    	}
    	if(allCourses != null)
    		return (qual == null)? allCourses : 
    			EOQualifier.filteredArrayWithQualifier(allCourses, qual);
    	if(EduCycle.entityName.equals("PlanCycle")) {
    		allCourses = EOUtilities.objectsMatchingKeyAndValue(ec,EduCycle.entityName,
    				"school",session().valueForKey("school"));
    		EOQualifier[] quals = new EOQualifier[2];
    		quals[0] = Various.getEOInQualifier("cycle", allCourses);
    		quals[1] = new EOKeyValueQualifier("eduYear",EOQualifier.QualifierOperatorEqual,
    				session().valueForKey("eduYear"));
    		quals[0] = new EOAndQualifier(new NSArray(quals));
    		EOFetchSpecification fs = new EOFetchSpecification(EduCourse.entityName,quals[0],null);
    		allCourses = ec.objectsWithFetchSpecification(fs);
    	} else {
    		allCourses = EOUtilities.objectsMatchingKeyAndValue(ec,
    				EduCourse.entityName, "eduYear", session().valueForKey("eduYear"));
    	}
    	if(allCourses != null && allCourses.count() > 1)
    		sort();
		return (qual == null)? allCourses : 
			EOQualifier.filteredArrayWithQualifier(allCourses, qual);
    }
    
    protected void sort() {
  		if(grouping.equals("eduGroup"))
			allCourses = EOSortOrdering.sortedArrayUsingKeyOrderArray(allCourses, byClass);
		else if(grouping.equals("cycle"))
			allCourses = EOSortOrdering.sortedArrayUsingKeyOrderArray(allCourses, bySubject);
		else if(grouping.equals("teacher"))
			allCourses = EOSortOrdering.sortedArrayUsingKeyOrderArray(allCourses, byTeacher);
    }
    
    public void setGrouping(String newGrouping) {
    	grouping = newGrouping;
    	if(allCourses != null && allCourses.count() > 1)
    		sort();
    }
    
    public String groupLink() {
    	if(courseID instanceof NSDictionary) {
    		Object idx = ((NSDictionary)courseID).valueForKey("idx");
    		return grHead + idx + ".html";
    	} else {
    		return grHead + ".html";
    	}
    }
    
    public String style() {
    	if(courseID instanceof NSDictionary) {
    		if(!grHead.equals(grouping))
    			return null;
    		Object idx = ((NSDictionary)courseID).valueForKey("idx");
    		if (idx.equals(session().valueForKeyPath("state.section.idx")))
    			return "font-weight:bold;";
    	} else if (grHead.equals(grouping)) {
    		return "font-weight:bold;";
    	} else if (grHead.equals("teacher")) {
    		return null;
    	} else if (Various.boolForObject(application().valueForKeyPath(
    				"strings.sections.hasSections"))) {
    		return "font-style:italic;";
    	}
    	return null;
    }
    
    public boolean showSections() {
    	return (!grHead.equals("teacher") &&  Various.boolForObject(application().valueForKeyPath(
    				"strings.sections.hasSections")));
    }
    
    public String groupTitle() {
    	return (String)session().valueForKeyPath("strings.RujelComplete_Complete." + grHead);
    }
    
    public void setItem(EduCourse course) {
    	grHead = null;
    	if(course == null) {
    		courseID = null;
    		item = null;
    		return;
    	}
    	EOKeyGlobalID gid = (EOKeyGlobalID)ec.globalIDForObject(course);
    	courseID = gid.keyValues()[0];
		if(item != null && grouping.equals("cycle")){
			if(item.cycle().subject().equals(course.cycle().subject())) {
				item = course;
				return;
			}
		}
    	if(item == null || item.valueForKey(grouping) != course.valueForKey(grouping)) {
    		StringBuilder buf = new StringBuilder("</div>");
    		buf.append("\n<div class=\"gr\"");
    		buf.append(" onmouseover = \"dim(this);\" onmouseout = \"unDim(this);\"");
    		buf.append(" onclick = \"toggleObj('gr").append(courseID).append("');\">");
    		if(grouping.equals("eduGroup"))
    			buf.append(course.eduGroup().name());
    		else if(grouping.equals("cycle"))
    			buf.append(course.cycle().subject());
    		else if(grouping.equals("teacher"))
    			buf.append(Person.Utility.fullName(course.teacher(), true, 2, 1, 1));
    		buf.append("</div>\n<div style=\"display:none;padding-left:1em;\" id=\"gr");
    		buf.append(courseID).append("\">\n");
    		grHead = buf.toString();
    	}
    	item = course;
    }
    
    public String present() {
    	if(courseID == null)
    		return null;
    	int state = 10;
    	if(catalog != null) {
        	NSDictionary crDict = null;
    		crDict = (NSDictionary)catalog.valueForKey(courseID.toString());
    		if(crDict != null && crDict.count() > 0) {
    			Enumeration enu = crDict.objectEnumerator();
    			while (enu.hasMoreElements()) {
					if(!Various.boolForObject(enu.nextElement())) {
						state = 5;
						break;
					}
				}
    		} else {
    			state = 0;
    		}
    	}
    	StringBuilder buf = new StringBuilder(50);
    	if(state > 0) {
    		buf.append("<a href = \"");
    		if(sections)
    			buf.append('S').append(item.valueForKeyPath("cycle.section")).append('/');
    		buf.append(courseID).append("/index.html\"");
    		if(state < 10)
    			buf.append(" class = \"partial\"");
    		buf.append(" onclick = \"updateFrame(this.href);\">");
    	} else {
    		buf.append("<div style = \"color:#999999;\">");
    	}
		buf.append("<span style=\"float:left;\">");
    	if(!grouping.equals("eduGroup"))
    		buf.append(item.eduGroup().name());
    	if(!grouping.equals("cycle")) {
    		if(grouping.equals("teacher"))
    			buf.append("</span>\n<span style=\"float:right;\">");
    		buf.append(item.subjectWithComment());
    	} else if(item.comment() != null) {
    			buf.append(" (").append(item.comment()).append(')');
    	}
    	if(!grouping.equals("teacher")) {
    		buf.append("</span>\t<span class=\"teach\">");
    		buf.append(Person.Utility.fullName(item.teacher(), true, 2, 1, 1));
    	}
    	buf.append("</span>\n");
    	if(state > 0)
    		buf.append("</a>");
    	else
    		buf.append("</div>");
    	return buf.toString();
    }
    
    public static void prepareCourses(FileWriterUtil exec,
    		NSKeyValueCoding catalog, boolean write) {
		NSDictionary sect = (NSDictionary)WOApplication.application().valueForKeyPath(
				"strings.sections");
		NSArray list = null;
		if(Various.boolForObject(sect.valueForKey("hasSections"))) {
				list = (NSArray)sect.valueForKey("list");
				sect = (NSDictionary)list.objectAtIndex(0);
		} else {
			sect = null;
		}
    	if(catalog == null) {
    		String filename = (sect == null)?"eduGroup.html":
    			"eduGroup" + sect.valueForKey("idx") + ".html";
    		Executor.prepareFolder(exec, filename);
    	}
    	EOEditingContext ec = exec.ctx.session().defaultEditingContext();
		CoursesCatalog page = new CoursesCatalog(exec.ctx);
		page.takeValueForKey(ec, "ec");
		page.takeValueForKey(catalog, "catalog");
		page.takeValueForKey("teacher", "grouping");
		exec.writeFile("teacher.html", page);
		if(list == null) {
			page.takeValueForKey("cycle", "grouping");
			exec.writeFile("cycle.html", page);
			page.takeValueForKey("eduGroup", "grouping");
			exec.writeFile("eduGroup.html", page);
		} else {
			Enumeration enu = list.objectEnumerator();
			WOSession ses = exec.ctx.session();
			sect = (NSDictionary)ses.valueForKeyPath("state.section");
			while (enu.hasMoreElements()) {
				NSDictionary s = (NSDictionary)enu.nextElement();
				Integer idx = (Integer)s.valueForKey("idx");
				ses.takeValueForKeyPath(s, "state.section");
				page.takeValueForKey("cycle", "grouping");
				exec.writeFile("cycle" + idx + ".html", page);
				page.takeValueForKey("eduGroup", "grouping");
				exec.writeFile("eduGroup" + idx + ".html", page);
			}
			ses.takeValueForKeyPath(sect, "state.section");
		}
		if(write) {
			NSArray courses = page.allCourses;
			NSArray reports = (NSArray)exec.ctx.session().valueForKeyPath(
					"modules.courseComplete");
			Enumeration enu = courses.objectEnumerator();
			int progress = 0;
			NSMutableDictionary dateForList = new NSMutableDictionary();
			NSTimestamp activeDate = (NSTimestamp)exec.ctx.session().valueForKey("today");
			while (enu.hasMoreElements()) {
				EduCourse course = (EduCourse) enu.nextElement();
				EOKeyGlobalID gid = (EOKeyGlobalID)ec.globalIDForObject(course);
				String key = gid.keyValues()[0].toString();
				NSDictionary crDict = null;
				if(catalog != null) {
					crDict = (NSDictionary)catalog.valueForKey(key);
					if(crDict == null || crDict.count() == 0)
						continue;
				} else {
					EOEditingContext tmpEC = new SessionedEditingContext(
							ec.parentObjectStore(), exec.ctx.session(), false);
					tmpEC.lock();
					course = (EduCourse)EOUtilities.localInstanceOfObject(tmpEC, course);
				}
				String listName = SettingsBase.stringSettingForCourse(
						EduPeriod.ENTITY_NAME, course, ec);
				NSTimestamp date = (NSTimestamp)dateForList.valueForKey(listName);
				if(date == null) {
					NSArray periods = EduPeriod.periodsInList(listName, ec);
					boolean dflt = (periods == null || periods.count() == 0);
					if(dflt) {
						date = (NSTimestamp)dateForList.valueForKey("DEFAULT");
						dflt = (date==null);
						if(dflt)
							periods = EduPeriod.defaultPeriods(ec);
					}
					if(periods != null && periods.count() > 0) {
						EduPeriod per = (EduPeriod)periods.lastObject();
						date = per.end();
					}
					if(date == null)
						date = activeDate;
					if(dflt)
						dateForList.takeValueForKey(date, "DEFAULT");
					dateForList.takeValueForKey(date, listName);
				}
				if(!date.equals(activeDate)) {
					activeDate = date;
					exec.ctx.session().takeValueForKey(date, "today");
				}
//				File cDir = new File(folder,key);
				{
					progress++;
					StringBuilder buf = new StringBuilder(10);
					buf.append(progress).append(" / ").append(courses.count());
					Executor.progress().takeValueForKey(buf.toString(), "progress");
				}
				CoursePage.printCourseReports(course, exec, key, reports, crDict);
				if(catalog == null) {
					course.editingContext().unlock();
					course.editingContext().dispose();
				}
			}
		}
    }
}