// StudentCatalog.java: Class file for WO Component 'StudentCatalog'

/*
 * Copyright (c) 2008, Gennady & Michael Kushnir
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without modification, are
 * permitted provided that the following conditions are met:
 * 
 * 	•	Redistributions of source code must retain the above copyright notice, this
 * 		list of conditions and the following disclaimer.
 * 	•	Redistributions in binary form must reproduce the above copyright notice,
 * 		this list of conditions and the following disclaimer in the documentation
 * 		and/or other materials provided with the distribution.
 * 	•	Neither the name of the RUJEL nor the names of its contributors may be used
 * 		to endorse or promote products derived from this software without specific 
 * 		prior written permission.
 * 		
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
 * SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 * TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY
 * WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package net.rujel.complete;

import java.util.Enumeration;

import net.rujel.base.MyUtility;
import net.rujel.base.SchoolSection;
import net.rujel.base.Setting;
import net.rujel.base.SettingsBase;
import net.rujel.interfaces.*;
import net.rujel.io.XMLGenerator;
import net.rujel.reports.StudentReports;
import net.rujel.reusables.AdaptingComparator;
import net.rujel.reusables.SessionedEditingContext;
import net.rujel.reusables.Various;
import net.rujel.reusables.FileWriterUtil;
import net.rujel.reusables.WOLogLevel;

import com.webobjects.appserver.*;
import com.webobjects.eoaccess.EOUtilities;
import com.webobjects.eocontrol.EOEditingContext;
import com.webobjects.eocontrol.EOKeyGlobalID;
import com.webobjects.foundation.NSArray;
import com.webobjects.foundation.NSData;
import com.webobjects.foundation.NSDictionary;
import com.webobjects.foundation.NSKeyValueCoding;
import com.webobjects.foundation.NSMutableArray;
import com.webobjects.foundation.NSMutableDictionary;

import com.webobjects.foundation.NSTimestamp;

// Generated by the WOLips Templateengine Plug-in at Jun 17, 2009 8:06:10 PM
public class StudentCatalog extends com.webobjects.appserver.WOComponent {
	
	public NSArray eduGroups;
	public EduGroup group;
	public String groupID;
	public Student student;
	public EOEditingContext ec;
	public NSKeyValueCoding catalog;
	public NSKeyValueCoding grDict;
	protected String grFolder;
	public boolean grReports;
	public int total;
	public String defaultReport;
	
    public StudentCatalog(WOContext context) {
        super(context);
    }
    
    public void appendToResponse(WOResponse aResponse, WOContext aContext) {
    	total = 0;
    	super.appendToResponse(aResponse, aContext);
    }
    
    public void setGroup(EduGroup newGroup) {
    	group = newGroup;
    	if(group == null) {
    		groupID = null;
    		grDict = null;
    		list = null;
    		grFolder = null;
    		return;
    	}
    	if(ec == null)
    		ec = group.editingContext();
    	list = group.list();
    	total += list.count();
    	EOKeyGlobalID gid = (EOKeyGlobalID) ec.globalIDForObject(group);
    	groupID = "gr" + gid.keyValues()[0];
    	StringBuilder buf = new StringBuilder(7);
    	buf.append(group.grade()).append('_').append(gid.keyValues()[0]);
    	grFolder = buf.toString();
    	if(catalog != null)
    		grDict = (NSDictionary)catalog.valueForKey(grFolder);
    }
    
    public String ready() {
    	StringBuilder buf = new StringBuilder("<span style = \"float:right\">");
    	if(catalog == null) {
    	} else if(grDict == null) {
    		buf.append("&oslash;");
    	} else {
    		int count = 0;
    		Enumeration enu = ((NSDictionary)grDict).objectEnumerator();
    		while (enu.hasMoreElements()) {
				if(Various.boolForObject(enu.nextElement()))
						count++;
			}
    		if(count < list.count())
    			buf.append(count).append('/');
    	}
    	buf.append(list.count());
    	buf.append("</span>");
    	return buf.toString();
    }
    
    public String studentLink() {
       	StringBuilder result = new StringBuilder(30);
       	result.append(grFolder).append('/');
    	if(student == null) {
    		result.append("group");
    	} else {
           	EOKeyGlobalID gid = (EOKeyGlobalID) ec.globalIDForObject(student); 
           	result.append(gid.keyValues()[0]);
    	}
       	result.append("/index.html");
       	return result.toString();
    }
    
    public String onclick() {
    	return "toggleObj('" + groupID + "');";
    }

    public NSArray list;
    
    public static void prepareStudents(FileWriterUtil folder) {
    	WOSession ses = folder.ctx.session();
    	EOEditingContext ec = ses.defaultEditingContext();
		NSKeyValueCoding sect = (NSDictionary)ses.valueForKeyPath("sections");
		NSArray grReports = (NSArray)ses.valueForKeyPath("modules.groupComplete");
		if(grReports != null && grReports.count() == 0)
			grReports = null;
		NSArray groups = null;
		StudentReports studentReports = new StudentReports(ses);
		if(Various.boolForObject(sect.valueForKey("hasSections"))) {
			NSArray list = (NSArray)sect.valueForKey("list");
			sect = (SchoolSection)list.objectAtIndex(0);
			Executor.prepareFolder(folder, "list" + sect.valueForKey("sectionID") + ".html");
			Enumeration enu = list.objectEnumerator();
			sect = (SchoolSection)ses.valueForKeyPath("state.section");
			NSMutableArray allGroups = new NSMutableArray();
			while (enu.hasMoreElements()) {
				SchoolSection item = (SchoolSection) enu.nextElement();
				ses.takeValueForKeyPath(item, "state.section");
		    	groups = EduGroup.Lister.listGroups((NSTimestamp)ses.valueForKey("today"), ec);
		    	allGroups.addObject(item);//EOUtilities.localInstanceOfObject(ec, item));
		    	allGroups.addObjectsFromArray(groups);
		    	WOComponent page = WOApplication.application().pageWithName("StudentCatalog",
		    			folder.ctx);
		    	page.takeValueForKey(ec, "ec");
		    	page.takeValueForKey(groups, "eduGroups");
		    	page.takeValueForKey(studentReports.defaultID(), "defaultReport");
		    	page.takeValueForKey(Boolean.valueOf(grReports != null), "grReports");
		    	folder.writeFile("list" + item.sectionID() + ".html", page);
			}
			groups = allGroups;
			ses.takeValueForKeyPath(sect, "state.section");
		} else {
	    	Executor.prepareFolder(folder, "list.html");
			sect = (SchoolSection)ses.valueForKeyPath("state.section");
	    	groups = EduGroup.Lister.listGroups((NSTimestamp)ses.valueForKey("today"), ec);
	    	WOComponent page = WOApplication.application().pageWithName("StudentCatalog",
	    			folder.ctx);
	    	page.takeValueForKey(ec, "ec");
	    	page.takeValueForKey(groups, "eduGroups");
	    	page.takeValueForKey(Boolean.valueOf(grReports != null), "grReports");
	    	folder.writeFile("list.html", page);
		}
		Enumeration grenu = groups.objectEnumerator();
		Integer year = (Integer) ses.valueForKey("eduYear");
		int[] idx = new int [] {0,0};
		while (grenu.hasMoreElements()) {
			Object next = grenu.nextElement();
			if(next instanceof SchoolSection) {
				ses.takeValueForKeyPath(next, "state.section");
				idx[0]++;
				continue;
			}
			System.gc();
			EduGroup gr = (EduGroup) next;
//			File grDir = new File(folder,groupDirName(gr));
			EOEditingContext tmpEC = new SessionedEditingContext(
					ec.parentObjectStore(), folder.ctx.session(), false);
			tmpEC.lock();
			gr = (EduGroup)EOUtilities.localInstanceOfObject(tmpEC, gr);
			String grDir = groupDirName(gr,true);
			folder.enterDir(grDir, false);
			grDir = gr.name();
			NSArray list = gr.list();
			if(grReports != null) {
				completeGroup(gr, list, grReports, folder);
			}
			NSArray args = new NSArray(new Object[] {year, gr });
			NSArray existingCourses = EOUtilities.objectsWithQualifierFormat(tmpEC,
					EduCourse.entityName,"eduYear = %d AND eduGroup = %@",args);
			NSMutableDictionary grxml = (NSMutableDictionary)folder.ctx.userInfoForKey("grxml");
			if(grxml == null) {
				grxml = new NSMutableDictionary();
				folder.ctx.setUserInfoForKey(grxml, "grxml");
			}
			try {
				if(existingCourses != null && existingCourses.count() > 1)
					existingCourses = existingCourses.sortedArrayUsingComparator(
							new AdaptingComparator());
				NSMutableDictionary settings = new NSMutableDictionary(gr, "eduGroup");
				settings.takeValueForKey(existingCourses,"courses");
				settings.takeValueForKey(gr.list(),"students");
				NSMutableDictionary counters = new NSMutableDictionary();
				settings.takeValueForKey(counters, "counters");
				byte[] fullData = XMLGenerator.generate(ses, settings);
				grxml.takeValueForKey(settings.valueForKey("persons"), "persons");
				grxml.takeValueForKey(fullData, "fullData");
				grxml.takeValueForKey(new Integer(counters.count()),"counters");
				grxml.takeValueForKey(gr,"gr");
				if(counters.count() > 0)
					folder.writeData("raw.xml", new NSData(fullData));
			} catch (Exception e) {
				Executor.logger.log(WOLogLevel.WARNING,"Error generating group xml",
						new Object[] {ses,gr,e});
			}

			Enumeration stenu = list.objectEnumerator();
			idx[0]++;
			idx[1] = 0;
			while (stenu.hasMoreElements()) {
				{
					StringBuilder buf = new StringBuilder();
					buf.append(idx[0]).append(" / ").append(groups.count());
					buf.append(" [ ").append(grDir).append(": ");
					buf.append(idx[1]++).append(" / ").append(list.count()).append(" ]");
					Executor.progress().takeValueForKey(buf.toString(), "progress");
				}
				Student student = (Student) stenu.nextElement();
//		    	EOKeyGlobalID gid = (EOKeyGlobalID)student.editingContext().globalIDForObject(student);
//				File stDir = new File(grDir,gid.keyValues()[0].toString());
				completeStudent(gr, student, studentReports.reporterList(), existingCourses,
						folder);
			}
			tmpEC.unlock();
			tmpEC.dispose();
			folder.leaveDir();
		}
		ses.takeValueForKeyPath(sect, "state.section");
	}

    public static String groupDirName(EduGroup gr, boolean endslash) {
		EOKeyGlobalID gid = (EOKeyGlobalID)gr.editingContext().globalIDForObject(gr);
		StringBuilder filename = new StringBuilder(12);
		filename.append(gr.grade()).append('_');
		filename.append(gid.keyValues()[0]);
		if (endslash)
			filename.append('/');
		return filename.toString();
//		return new File(folder,filename.toString());
    }
    /*
    public static void writeGroup(EduGroup gr,NSArray students, NSArray reports,
    		File folder,Integer year, WOContext ctx) {
    	EOEditingContext ec = gr.editingContext();
		if(students == null)
			students = gr.list();
		Enumeration stenu = students.objectEnumerator();
		NSArray args = new NSArray(new Object[] {year, gr });
		NSArray existingCourses = EOUtilities.objectsWithQualifierFormat(ec,
				EduCourse.entityName,"eduYear = %d AND eduGroup = %@",args);
		File grDir = groupDir(folder, gr);
		while (stenu.hasMoreElements()) {
			Student student = (Student) stenu.nextElement();
			completeStudent(gr, student, reports, existingCourses, grDir, ctx, false);
		}
    } */
    public static void completeGroup(EduGroup gr, NSArray list, NSArray reports, 
    		FileWriterUtil exec) {
    	exec.enterDir("group", false);
		WOComponent page = WOApplication.application().pageWithName("StudentPage", exec.ctx);
		page.takeValueForKey(gr, "eduGroup");
		page.takeValueForKey(reports, "reports");
		exec.writeFile("index.html", page);
		Enumeration repEnu = reports.objectEnumerator();
		if(list != null) {
			NSDictionary dict = SettingsBase.courseDict(gr);
			EOEditingContext ec = gr.editingContext(); 
			Setting active = SettingsBase.settingForCourse("CompletionActive",dict, ec);
			if(Various.boolForObject(active.textValue())) {
				list = Completion.findCompletions(null, list, "student", Boolean.TRUE, ec);
				NSArray more = Completion.findCompletions(null, 
						NSKeyValueCoding.NullValue, "student", Boolean.TRUE, ec);
				if(list == null || list.count() == 0) {
					list = more;
				} else if(more != null && more.count() > 0) {
					list = list.arrayByAddingObjectsFromArray(more);
				}
			} else {
				list = null;
			}
		}
		while (repEnu.hasMoreElements()) {
			NSDictionary reporter = (NSDictionary) repEnu.nextElement();
			String id = (String)reporter.valueForKey("id");
			String name = (String)reporter.valueForKey("component");
			page = WOApplication.application().pageWithName(name,exec.ctx);
			if(list != null)
				page.takeValueForKey(list,"complete");
			try {
				page.takeValueForKey(NSDictionary.EmptyDictionary, "pedsovet");
				page.takeValueForKey(PedDecision.dictForGroup(gr), "pedsovet");
			} catch (NSKeyValueCoding.UnknownKeyException e) {}
			page.takeValueForKey(gr,"eduGroup");
			exec.writeFile(id + ".html", page);
		}
		exec.leaveDir();
    }    
    public static void completeStudent(EduGroup gr, Student student, NSArray reports,
    		NSArray existingCourses, FileWriterUtil exec) {
    	EOKeyGlobalID gid = (EOKeyGlobalID)student.editingContext().globalIDForObject(student);
    	exec.enterDir(gid.keyValues()[0].toString(), false);
//		if(!stDir.exists())
//			stDir.mkdirs();
		NSKeyValueCoding page = WOApplication.application().pageWithName("StudentPage", exec.ctx);
		page.takeValueForKey(student, "student");
		page.takeValueForKey(gr, "eduGroup");
		page.takeValueForKey(reports, "reports");
		exec.writeFile("index.html", (WOComponent)page);
/*		reportsForStudent(reports, student, ctx, existingCourses, stDir, overwrite);
    }
    private static void reportsForStudent(NSArray reports, Student student, WOContext ctx,
    		NSArray existingCourses, File stDir, boolean overwrite) { */
		Enumeration repEnu = reports.objectEnumerator();
		NSArray array = new NSArray(student);
		while (repEnu.hasMoreElements()) {
			NSDictionary reporter = (NSDictionary) repEnu.nextElement();
			boolean xml = (reporter.valueForKey("component") == null);
			if(xml)
				page = new NSMutableDictionary();
			else
				page = WOApplication.application().pageWithName("PrintReport",exec.ctx);
			page.takeValueForKey(reporter,"reporter");
			page.takeValueForKey(existingCourses,"courses");
			page.takeValueForKey(gr, "eduGroup");
			page.takeValueForKey(array,"students");
			String filename = reporter.valueForKey("id") + ".html";
			if(xml) {
				if(reporter.valueForKey("transform") == null)
					continue;
				WOSession ses = exec.ctx.session();
				NSMutableDictionary info = new NSMutableDictionary(MyUtility.presentEduYear(
						(Integer)ses.valueForKey("eduYear")), "eduYear");
				page.takeValueForKey(info, "info");
				if(Various.boolForObject(reporter.valueForKeyPath("settings.courses.hidden"))) {
					SettingsBase reportCourses = SettingsBase.baseForKey(
							"reportCourses", gr.editingContext(), false);
					page.takeValueForKey(reportCourses, "reportCourses");
				}
				NSMutableDictionary counters = new NSMutableDictionary();
				page.takeValueForKey(counters, "counters");
				try {
					byte[] report;
					if(Various.boolForObject(reporter.valueForKey("studentInOptions"))) {
						NSMutableDictionary grxml = (NSMutableDictionary)exec.ctx.userInfoForKey(
						"grxml");
						if(grxml == null) {
							grxml = new NSMutableDictionary();
							exec.ctx.setUserInfoForKey(grxml, "grxml");
						}
						page.takeValueForKey(student,"student");
						byte[] fullData;
						if(grxml.valueForKey("gr") != gr) {
							Executor.Task task =
								(Executor.Task)exec.ctx.userInfoForKey("Executor$Task");
							page.takeValueForKey(null,"reporter");
							if(task != null && task.studentIDs != null 
									&& task.studentIDs.length > 0) {
								NSMutableArray students =
									new NSMutableArray(task.studentIDs.length);
								EOEditingContext ec = gr.editingContext();
								for (int i = 0; i < task.studentIDs.length; i++) {
									students.addObject(ec.faultForGlobalID(task.studentIDs[i], ec));
								}
								page.takeValueForKey(students,"students");
							} else {
								page.takeValueForKey(gr.list(),"students");
							}
							fullData = XMLGenerator.generate(ses, (NSMutableDictionary)page);
							grxml.takeValueForKey(page.valueForKey("persons"), "persons");
							grxml.takeValueForKey(fullData, "fullData");
							grxml.takeValueForKey(new Integer(counters.count()),"counters");
							grxml.takeValueForKey(gr,"gr");
							page.takeValueForKey(reporter,"reporter");
						} else {
							page.takeValueForKey(null,"students");
							page.takeValueForKey(grxml.valueForKey("persons"), "persons");
							fullData = (byte[])grxml.valueForKey("fullData");
						}
						report = XMLGenerator.transformData(ses, (NSDictionary)page, fullData);
					} else { // studentInOptions
						report = XMLGenerator.generate(ses, (NSMutableDictionary)page);
					}
					if(report != null && report.length > 1) {
						NSData data = new NSData(report);
						exec.writeData(filename, data);
					}
				} catch (Exception e) {
					Executor.logger.log(WOLogLevel.WARNING,"Error generating " + filename,
							new Object[] {ses,e});
				}
			} else {
				exec.writeFile(filename, (WOComponent)page);
			}
		}
		exec.leaveDir();
    }

	public Boolean studentNotReady() {
		if(catalog == null)
			return Boolean.FALSE;
		if(grDict == null)
			return Boolean.TRUE;
		EOKeyGlobalID gid = (EOKeyGlobalID) ec.globalIDForObject(student); 
		String key = gid.keyValues()[0].toString();
		return Boolean.valueOf(!Various.boolForObject(grDict.valueForKey(key)));
	}
	
	public String sectionHref() {
		StringBuilder buf = new StringBuilder("list");
		buf.append(grDict.valueForKey("sectionID"));
		buf.append(".html");
		return buf.toString();
	}
	
	public String style() {
		Object curSect = session().valueForKeyPath("state.section");
		if (curSect == grDict)
			return "font-weight:bold;";
		return null;
	}
}